version: "3.7"

services:
  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gis_test1
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - gis_test1_static:/data/static/
      - gis_test1_media:/data/media/

  django:
    image: gis_test1:4
    networks:
      - gis_test1
    volumes:
      - gis_test1_static:/home/gis_test1/staticfiles/
      - gis_test1_static:/home/gis_test1/meida/

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_test1
    volumes:
      - gis_test1_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234

networks:
  gis_test1:

volumes:
  gis_test1_static:
  gis_test1_media:
  gis_test1_mariadb: